GESTION_DE_BILLET_beta2/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('client.urls')),
    path('',include('dashboard.urls')),
    path('',include('companyman.urls')),
]

client/urls.py
from django.urls import path
from . import views

app_name="client"

urlpatterns = [
    path('',views.accueil_view,name='accueil'),
    path('suggestion/',views.suggestionForm,name='suggestion'),
    path('etape1/',views.reservation1_view,name='etape1'),
    path('etape3/<int:billet_id>/',views.billet_detail_view,name='billet_detail_view'),
    path('etape2/<int:res_id>/',views.reservation2_view,name='etape2'),
    path('infoligne/<int:ln_id>/',views.infoligne_view, name='infoligne'),
]

templates/base0.html
<!DOCTYPE html>
{% load static %}

{% load crispy_forms_tags %}

<html lang="fr">

<head>
  <title>
    {% block titre %}

    {% endblock titre %}
  </title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <link rel="stylesheet" href="{% static 'layout.css' %}" type="text/css" media="all">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/framework.css' %}">
  <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
  <link rel="stylesheet" href="{% static 'bootstrap4/assets/css/docs.min.css' %}">
  <link rel="stylesheet" href="{% static 'bootstrap5/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'bootstrap5/layout.css' %}">
  <link rel="stylesheet" href="{% static 'fontawesome/css/all.min.css' %}">
  <script type="text/javascript" src="{% static 'bootstrap5/js/bootstrap.min.js' %}"></script>
  <script type="text/javascript" src=" {% static 'DataTables/media/js/jquery.js' %} "></script>
  <script type="text/javascript" src=" {% static 'DataTables/media/js/jquery.dataTables.min.js' %} "></script>
  <script type="text/javascript" src=" {% static 'DataTable/result.js' %} "></script>
  <link rel="stylesheet" type="text/css" href=" {% static 'DataTables/media/css/jquery.dataTables.min.css' %} ">

  {% block headcomplement %}

  {% endblock headcomplement %}



</head>

<body id="top">

  <!-- ################################################################################################ -->
  <!-- ################################################################################################ -->
  <!-- ################################################################################################ -->

  <div class="wrapper row0">

    <div id="topbar" class="hoc clear">
      <!-- ################################################################################################ -->
      <div class="fl_left">
        <ul>
          <li><i class="fa fa-phone"></i> +228 90 00 00 09</li>
          <li><i class="fa fa-envelope-o"></i> akstransport@gmail.com</li>
        </ul>
      </div>
      <!-- ################################################################################################ -->
    </div>
  </div>
  <!-- ################################################################################################ -->
  <!-- ################################################################################################ -->
  <!-- ################################################################################################ -->
  <div class="wrapper row1">
    <header id="header" class="hoc clear">
      <!-- ################################################################################################ -->
      <div id="logo" class="fl_left">
        <img src="{% static 'images/logo1.png' %}" alt="">
        {% now 'd/m/Y H:i:s' %}
      </div>

      <!-- ################################################################################################ -->
    </header>
    {% block contenu %}

    {% endblock contenu %}
  </div>
</body>

</html>

templates/base1.html
<!DOCTYPE html>
{% load static %}

{% load crispy_forms_tags %}

<html lang="fr">

<head>
  <title>
    {% block titre %}

    {% endblock titre %}
  </title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <link rel="stylesheet" href="{% static 'layout.css' %}" type="text/css" media="all">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/framework.css' %}">
  <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
  <link rel="stylesheet" href="{% static 'bootstrap4/assets/css/docs.min.css' %}">
  <link rel="stylesheet" href="{% static 'bootstrap5/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'bootstrap5/layout.css' %}">
  <link rel="stylesheet" href="{% static 'fontawesome/css/all.min.css' %}">
  <!-- <script type="text/javascript" src=""></script> -->
  <!-- <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script> -->
  <script type="text/javascript" src="{% static 'bootstrap5/js/bootstrap.min.js' %}"></script>
  <script type="text/javascript" src=" {% static 'DataTables/media/js/jquery.js' %} "></script>
  <script type="text/javascript" src=" {% static 'DataTables/media/js/jquery.dataTables.min.js' %} "></script>
  <script type="text/javascript" src=" {% static 'DataTable/result.js' %} "></script>
  <link rel="stylesheet" type="text/css" href=" {% static 'DataTables/media/css/jquery.dataTables.min.css' %} ">

  {% block headcomplement %}

  {% endblock headcomplement %}



</head>

<body oncontextmenu="return false" class="snippet-body">
    <div class="wrapper row0">

        <div id="topbar" class="hoc clear">
          <!-- ################################################################################################ -->
          <div class="fl_left">
            <ul>
              <li><i class="fa fa-phone"></i> +228 90 00 00 09</li>
              <li><i class="fa fa-envelope-o"></i> akstransport@gmail.com</li>
            </ul>
          </div>
          <!-- ################################################################################################ -->
        </div>
      </div>
      <!-- ################################################################################################ -->
      <!-- ################################################################################################ -->
      <!-- ################################################################################################ -->
      <div class="wrapper row1">
        <header id="header" class="hoc clear">
          <!-- ################################################################################################ -->
          <div id="logo" class="fl_left">
            <img src="{% static 'images/logo1.png' %}" alt="">
            {% now 'd/m/Y H:i:s' %}
          </div>
    
          <!-- ################################################################################################ -->
        </header>
        {% block contenu %}
    
        {% endblock contenu %}
      </div>
</body>

</html> 

templates/billet_detail.html
<!DOCTYPE html>
<h2>Billet #{{ billet.id }}</h2>
<p><strong>Nom :</strong> {{ billet.nom_clt }}</p>
<p><strong>Prénom :</strong> {{ billet.prenom_clt }}</p>
<p><strong>Email :</strong> {{ billet.email_clt }}</p>
<p><strong>Téléphone :</strong> {{ billet.telephone_clt }}</p>
<p><strong>Code du billet :</strong> {{ billet.code_billet }}</p>
<p><strong>Ligne :</strong> {{ billet.infoligne_id }}</p>
<p><strong>Prix unitaire :</strong> {{ billet.prix }}</p>
<p><strong>Nombre de places :</strong> {{ billet.place }}</p>
<p><strong>Montant total :</strong> {{ billet.montant_billet }}</p>
<p><strong>Date et heure :</strong> {{ billet.date_heure }}</p>

templates/infoligne.html
<!DOCTYPE html>
{% extends 'base0.html' %}


{% block contenu %}
<div style="margin: auto;padding: auto; width: 1000px;">
  
    
    <caption><h4>LIGNE : {{ln.ville_dep.nom_ville}} - {{ln.ville_arr.nom_ville}}</h4> </caption>
    
    <div class="scrollable">
      <table id="tableau" class="display">
        <thead>
          <tr>
            <th>DATE ET HEURE DE DEPART</th>
            <th>COMPAGNIE</th>
            <th>PRIX (CFA)</th>
            <th>PLACES DISPONIBLE</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
        {% for i in infln %}    
          <tr>
            <td> {{i.date_dep}} </td>
            <td> {{ i.bus_id.compagnie_id.nom_cp }} </td>
            <td> {{i.prix}} </td>
            <td> {{i.bus_id.nb_place}} </td>
            <td>
              <footer><a class="btn" href="{% url 'client:etape2' i.id %}">Réserver &rsaquo;</a></footer>
            </td>
          </tr>
          {% endfor %}
    
        </tbody>
      </table>
    </div>
    <footer><a class="btn" href="{% url 'client:accueil' %} ">&laquo; Revenir en arrière</a></footer>
    <script>
      $(document).ready(function () {
        $('#tableau').DataTable({
            dom:'f',
            language: {
                url: "DataTables/media/french.json"},
        });
    });
    </script>
    </div>
{% endblock contenu %}
    

templates/listeCompagnies.html
<!DOCTYPE html>
{% extends 'base0.html' %}

templates/reservation_etape1.html
<!DOCTYPE html>
{% extends 'base0.html' %}


{% block contenu %}

<p></p>
<div style="margin: auto;padding: auto; width: 1000px;">
  <p>ETAPE N°1 : CHOIX DU PLAN DE VOYAGE</p>
    <caption><h1>{{ rdt.date_dep }}</h1></caption>
    
    
    <div class="scrollable">
      <table id="tableau" class="display">
        <thead>
          <tr>
            <th>LIGNE</th>
            <th>DATE ET HEURE DE DEPART</th>
            <th>COMPAGNIE</th>
            <th>PRIX (CFA)</th>
            <th>PLACES DISPONIBLE</th>
            <th>DECISION</th>
          </tr>
        </thead>
        <tbody>
        {% for i in infln %}    
          <tr>
            <td> {{i.ligne_id.ville_dep.ville_id.nom_ville}} - {{i.ligne_id.ville_arr.ville_id.nom_ville}} </td>
            <td> {{i.date_dep}} </td>
            <td> {{ i.bus_id.compagnie_id.nom_cp }} </td>
            <td> {{i.prix}} </td>
            <td> {{i.bus_id.nb_place}} </td>
            <td>
              <footer><a class="btn" href="{% url 'client:etape2' %}">Choisir &rsaquo;</a></footer>
            </td>
          </tr>
          {% endfor %}
    
        </tbody>
      </table>
    </div>
    <footer><a class="btn" href="{% url 'client:accueil' %} ">&laquo; Revenir en arrière</a></footer>
    
    <script>
      $(document).ready(function () {
        $('#tableau').DataTable({
            dom:'f',
            language: {
                url: "DataTables/media/french.json"},
        });
    });
    </script>
    </div>
{% endblock contenu %}
    

templates/reservation_etape2.html
<!DOCTYPE html>
{% extends 'base1.html' %}
{% load static %}

{% block contenu %}

<div class="bg-contact100">
    <h1 style="align-items: center;text-align: center; ">RESERVATION</h1>
    <div class="container-contact100">
        <div class="wrap-contact100">
            <div class="contact100-pic js-tilt" data-tilt>
                <img src="{% static 'images/modele-formulaire-inscription.avif' %}" alt="IMG">
            </div>
            <form class="contact100-form validate-form" method="post" action="#">
                
                <span class="contact100-form-title">
                    <b>Faites votre réservation</b> 
                </span>
                {% csrf_token %}
                <div class="wrap-input100 validate-input" data-validate="Un Nom est requi.">
                    {{ form1.nom_clt }}
                    <span class="focus-input100"></span>
                </div>
                <div class="wrap-input100 validate-input" data-validate="Un Prénom est requi">
                    {{ form1.prenom_clt }}
                    <span class="focus-input100"></span>
                </div>
                <div class="wrap-input100 validate-input" data-validate="Un email valide est requi.">
                    {{ form1.email_clt }}
                    <span class="focus-input100"></span>
                </div>
                <div class="wrap-input100 validate-input" data-validate="Un numéro de telephone valide est requi">
                    {{ form1.telephone_clt }}
                    <span class="focus-input100"></span>
                </div>
                <div class="wrap-input100 validate-input">
                    {{ lecode }}
                    <span class="focus-input100"></span>
                </div>
                <div class="wrap-input100 validate-input" data-validate="Vous devez selectionner le nombre de place">
                    {{ form1.place }}
                    <span class="focus-input100"></span>
                </div>
                
                <div class="container-contact100-form-btn">
                    <button class="contact100-form-btn" type="submit">
                        Valider
                    </button>
                </div>
                
            </form>
        </div>
    </div>
</div>
<script type="text/javascript"></script>
{% endblock contenu %}
    

templates/reservation_etape3.html
<!DOCTYPE html>
{% extends 'base1.html' %}
{% load static %}

{% block contenu %}

<div class="bg-contact100">
    <h1 style="align-items: center;text-align: center; ">Votre Billet : </h1>
    <div class="container-contact100">
        <div class="wrap-contact100">
           
            {{instance}}
          
        </div>
    </div>
</div>
<script type="text/javascript"></script>
{% endblock contenu %}
    

templates/suggestion.html
<!DOCTYPE html>
{% extends 'base0.html' %}


{% block titre %}
AKS-T | Suggestions
{% endblock titre %}

{% block headcomplement %}
<!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
<script src="https://cdn.jsdelivr.net/npm/jquery@3.6.4/dist/jquery.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script> -->
{% endblock headcomplement %}

{% block contenu %}

<div class="bg-contact100">
    <h1 style="align-items: center;text-align: center; ">SUGGESTIONS</h1>
    <div class="container-contact100">
        <div class="wrap-contact100">
            <div class="contact100-pic js-tilt" data-tilt>
                <img src="https://i.imgur.com/VRFiMzM.png" alt="IMG">
            </div>
            <form class="contact100-form validate-form" method="post">
                
                <span class="contact100-form-title">
                   Faites nous part de vos <b>suggestions</b> 
                </span>
                {% csrf_token %}
                <div class="wrap-input100 validate-input" data-validate="Un email valide est requi. Exemple: ex@abc.xyz">
                    
                    {{ form.email }}
                    <span class="focus-input100"></span>
                    <span class="symbol-input100">
                        <i class="fa fa-envelope" aria-hidden="true"></i>
                    </span>
                </div>
                <div class="wrap-input100 validate-input" data-validate="Un message est requi">
                    {{ form.message }}
                    <span class="focus-input100"></span>
                </div>
                <div class="container-contact100-form-btn">
                    <button class="contact100-form-btn">
                        Envoyer
                    </button>
                </div>
                
            </form>
        </div>
    </div>
</div>
<script type="text/javascript"></script>


{% endblock contenu %}